databases:
  - name: imdb-clone-db
    databaseName: imdb_clone
    user: imdb_user
    plan: free

services:
  - type: web
    name: imdb-clone-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "imdb-clone-taw8.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: imdb-clone-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: imdb-clone-redis
          property: connectionString

  - type: redis
    name: imdb-clone-redis
    ipAllowList: [] # only internal
    plan: free
